Repository sinfo/ng-sinfo-webapp, pull requests merged in 2023-02, with the labels that each got.

#322 Promocodes redesign
  src/app/app.module.ts
  src/app/user/promocodes/promocode.model.ts
  src/app/user/promocodes/promocodes-dialog/promocodes-dialog.component.css
  src/app/user/promocodes/promocodes-dialog/promocodes-dialog.component.html
  src/app/user/promocodes/promocodes-dialog/promocodes-dialog.component.ts
  src/app/user/promocodes/promocodes.component.css
  src/app/user/promocodes/promocodes.component.html
  src/app/user/promocodes/promocodes.component.ts
Labels: promocodes

#331 Feature: Microsoft Authentication
  package-lock.json
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/auth/auth.service.ts
  src/app/auth/login/login.component.css
  src/app/auth/login/login.component.html
  src/app/auth/login/login.component.ts
  src/app/auth/login/microsoft.component.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#337 Update 2.1.1
  Dockerfile
  package.json
  src/app/auth/login/login.component.css
  src/app/auth/login/login.component.html
  src/app/auth/login/login.component.ts
  src/styles.css
Labels: update

#332 Feature: Fetch everything from cannon
  src/app/company/company-cannon.service.ts
  src/app/company/company.service.ts
  src/app/events/event.service.ts
  src/app/landing-page/sponsors/sponsor.service.ts
  src/app/session/session.service.ts
  src/app/speakers/speaker.model.ts
  src/app/speakers/speaker.service.ts
  src/app/speakers/speakers.component.ts
  src/app/team/team.component.ts
  src/app/team/team.service.ts
  src/app/user/user.service.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: feature

#338 Update 2.2.0
  src/app/company/company-cannon.service.ts
  src/app/company/company.service.ts
  src/app/events/event.service.ts
  src/app/landing-page/sponsors/sponsor.service.ts
  src/app/session/session.service.ts
  src/app/speakers/speaker.model.ts
  src/app/speakers/speaker.service.ts
  src/app/speakers/speakers.component.ts
  src/app/team/team.component.ts
  src/app/team/team.service.ts
  src/app/user/user.service.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: update

#334 Feature: Reverse Links
  package-lock.json
  src/app/partials/qr-code-scanner/qr-code-scanner.component.css
  src/app/partials/qr-code-scanner/qr-code-scanner.component.html
  src/app/partials/qr-code-scanner/qr-code-scanner.component.ts
  src/app/user/link/link.component.html
  src/app/user/link/link.component.ts
  src/app/user/link/link.model.ts
  src/app/user/link/my-links/my-links.component.html
  src/app/user/link/my-links/my-links.component.ts
  src/app/user/speed-date-sign/speed-date-sign.component.ts
  src/app/user/user.component.html
  src/app/user/user.service.ts
Labels: feature

#339 Fix: Fix error with buttons' width
  src/app/auth/login/login.component.css
Labels: fix

#340 Fix: Fix related to links
  src/app/company/company-cannon.service.ts
  src/app/user/link/my-links/my-links.component.html
  src/app/user/user.service.ts
Labels: fix

#341 Feature: Feedback
  src/app/user/user.component.html
Labels: feature

#344 Fix: Fix qr code scanner output
  src/app/user/checkin/checkin.component.html
  src/app/user/checkin/checkin.component.ts
  src/app/user/promote/promote.component.html
  src/app/user/promote/promote.component.ts
  src/app/user/signature/signature.component.html
  src/app/user/signature/signature.component.ts
  src/app/user/speed-date-sign/speed-date-sign.component.html
  src/app/user/speed-date-sign/speed-date-sign.component.ts
  src/app/user/validate-card/validate-card.component.html
  src/app/user/validate-card/validate-card.component.ts
  src/app/user/workshop-validation/workshop-validation.component.html
  src/app/user/workshop-validation/workshop-validation.component.ts
Labels: fix

#345 Feature: Add achievement
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/session/session.service.ts
  src/app/user/achievements/achievement.model.ts
  src/app/user/achievements/achievement.service.ts
  src/app/user/achievements/achievements.component.ts
  src/app/user/add-achievement/add-achievement.component.css
  src/app/user/add-achievement/add-achievement.component.html
  src/app/user/add-achievement/add-achievement.component.ts
  src/app/user/speed-dates/speed-dates.component.ts
  src/app/user/user.component.html
Labels: feature

#342 Update 2.2.1
  package-lock.json
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/auth/login/login.component.css
  src/app/company/company-cannon.service.ts
  src/app/landing-page/stands/stands.component.html
  src/app/partials/qr-code-scanner/qr-code-scanner.component.css
  src/app/partials/qr-code-scanner/qr-code-scanner.component.html
  src/app/partials/qr-code-scanner/qr-code-scanner.component.ts
  src/app/session/session.service.ts
  src/app/user/achievements/achievement.model.ts
  src/app/user/achievements/achievement.service.ts
  src/app/user/achievements/achievements.component.ts
  src/app/user/add-achievement/add-achievement.component.css
  src/app/user/add-achievement/add-achievement.component.html
  src/app/user/add-achievement/add-achievement.component.ts
  src/app/user/checkin/checkin.component.html
  src/app/user/checkin/checkin.component.ts
  src/app/user/link/link.component.html
  src/app/user/link/link.component.ts
  src/app/user/link/link.model.ts
  src/app/user/link/my-links/my-links.component.html
  src/app/user/link/my-links/my-links.component.ts
  src/app/user/promote/promote.component.html
  src/app/user/promote/promote.component.ts
  src/app/user/signature/signature.component.html
  src/app/user/signature/signature.component.ts
  src/app/user/speed-date-sign/speed-date-sign.component.html
  src/app/user/speed-date-sign/speed-date-sign.component.ts
  src/app/user/speed-dates/speed-dates.component.ts
  src/app/user/user.component.html
  src/app/user/user.service.ts
  src/app/user/validate-card/validate-card.component.html
  src/app/user/validate-card/validate-card.component.ts
  src/app/user/workshop-validation/workshop-validation.component.html
  src/app/user/workshop-validation/workshop-validation.component.ts
  src/environments/environment.prod.ts
Labels: update

#348 Update 2.2.2
  src/environments/environment.prod.ts
Labels: update

#346 Feature: Production Website
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/landing-page/feedback/feedback.component.css
  src/app/landing-page/landing-page.component.css
  src/app/landing-page/landing-page.component.html
  src/app/landing-page/partners/partners.component.css
  src/app/landing-page/partners/partners.component.html
  src/app/landing-page/partners/partners.component.ts
  src/app/landing-page/schedule/schedule.component.css
  src/app/landing-page/schedule/schedule.component.html
  src/app/landing-page/sponsors/sponsors.component.css
  src/app/landing-page/sponsors/sponsors.component.html
  src/app/landing-page/sponsors/sponsors.component.ts
  src/app/landing-page/stands/stands.component.css
  src/app/landing-page/stands/stands.component.html
  src/app/session/session.component.css
  src/app/session/session.component.html
  src/app/session/session.component.ts
  src/app/speakers/speaker/speaker.component.css
  src/app/speakers/speaker/speaker.component.html
  src/app/speakers/speaker/speaker.component.ts
  src/app/speakers/speakers.component.css
  src/app/speakers/speakers.component.html
  src/app/sponsor/sponsor.component.css
  src/app/sponsor/sponsor.component.html
  src/app/sponsor/sponsor.component.ts
  src/app/team/team.component.css
  src/app/team/team.component.html
  src/app/team/team.component.ts
  src/app/user/my-profile/my-profile.component.css
  src/app/user/my-profile/my-profile.component.html
  src/assets/img/event-cards/networking.jpg
  src/assets/img/event-cards/opportunities.jpg
  src/assets/img/event-cards/presentation.jpg
  src/assets/img/event-cards/prizes.jpg
  src/assets/img/event-cards/speaker.jpg
  src/assets/img/event-cards/workshop.jpg
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/index.html
  src/styles.css
Labels: feature

#350 Update 2.2.3
  package.json
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/landing-page/feedback/feedback.component.css
  src/app/landing-page/feedback/feedback.component.html
  src/app/landing-page/landing-page.component.css
  src/app/landing-page/landing-page.component.html
  src/app/landing-page/landing-page.component.ts
  src/app/landing-page/partners/partners.component.css
  src/app/landing-page/partners/partners.component.html
  src/app/landing-page/partners/partners.component.ts
  src/app/landing-page/schedule/schedule.component.css
  src/app/landing-page/schedule/schedule.component.html
  src/app/landing-page/sponsors/sponsors.component.css
  src/app/landing-page/sponsors/sponsors.component.html
  src/app/landing-page/sponsors/sponsors.component.ts
  src/app/landing-page/stands/stands.component.css
  src/app/landing-page/stands/stands.component.html
  src/app/partials/qr-code-scanner/qr-code-scanner.component.html
  src/app/session/session.component.css
  src/app/session/session.component.html
  src/app/session/session.component.ts
  src/app/speakers/speaker/speaker.component.css
  src/app/speakers/speaker/speaker.component.html
  src/app/speakers/speaker/speaker.component.ts
  src/app/speakers/speakers.component.css
  src/app/speakers/speakers.component.html
  src/app/sponsor/sponsor.component.css
  src/app/sponsor/sponsor.component.html
  src/app/sponsor/sponsor.component.ts
  src/app/team/team.component.css
  src/app/team/team.component.html
  src/app/team/team.component.ts
  src/app/user/add-achievement/add-achievement.component.ts
  src/app/user/cv/cv.component.html
  src/app/user/link/link.component.css
  src/app/user/link/link.component.html
  src/app/user/link/my-links/my-links.component.css
  src/app/user/link/my-links/my-links.component.html
  src/app/user/my-profile/my-profile.component.css
  src/app/user/my-profile/my-profile.component.html
  src/app/user/promote/promote.component.css
  src/app/user/promote/promote.component.html
  src/app/user/promote/promote.component.ts
  src/app/user/user.component.css
  src/app/user/user.service.ts
  src/assets/img/event-cards/networking.jpg
  src/assets/img/event-cards/opportunities.jpg
  src/assets/img/event-cards/presentation.jpg
  src/assets/img/event-cards/prizes.jpg
  src/assets/img/event-cards/speaker.jpg
  src/assets/img/event-cards/workshop.jpg
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/styles.css
Labels: update

#351 Fix: Login buttons
  src/app/auth/login/login.component.css
  src/app/auth/login/login.component.html
  src/app/auth/login/login.component.ts
Labels: feature

#347 Feature: Confirmation dialog for delete link
  src/app/user/link/my-links/delete-link-dialog.html
  src/app/user/link/my-links/my-links.component.css
  src/app/user/link/my-links/my-links.component.ts
Labels: feature

#355 Feature: Share links with other users
  src/app/landing-page/landing-page.component.ts
  src/app/user/link/link.component.html
  src/app/user/link/link.component.ts
  src/app/user/link/link.model.ts
  src/app/user/link/my-links/my-links.component.html
  src/app/user/link/my-links/my-links.component.ts
  src/app/user/user.model.ts
  src/app/user/user.service.ts
Labels: feature

#356 Update 2.2.4
  src/app/app.module.ts
  src/app/auth/login/login.component.css
  src/app/auth/login/login.component.html
  src/app/auth/login/login.component.ts
  src/app/landing-page/landing-page.component.ts
  src/app/landing-page/schedule/schedule.component.css
  src/app/landing-page/schedule/schedule.component.html
  src/app/landing-page/sponsors/sponsors.component.css
  src/app/partials/qr-code-scanner/qr-code-scanner.component.css
  src/app/session/session.component.css
  src/app/session/session.model.ts
  src/app/session/session.service.ts
  src/app/speakers/speaker/speaker.component.css
  src/app/speakers/speakers.component.css
  src/app/sponsor/sponsor.component.css
  src/app/sponsor/sponsor.component.ts
  src/app/user/checkin/checkin.component.html
  src/app/user/checkin/checkin.component.ts
  src/app/user/link/link.component.html
  src/app/user/link/link.component.ts
  src/app/user/link/link.model.ts
  src/app/user/link/my-links/delete-link-dialog/delete-link-dialog.component.css
  src/app/user/link/my-links/delete-link-dialog/delete-link-dialog.component.html
  src/app/user/link/my-links/delete-link-dialog/delete-link-dialog.component.ts
  src/app/user/link/my-links/my-links.component.css
  src/app/user/link/my-links/my-links.component.html
  src/app/user/link/my-links/my-links.component.ts
  src/app/user/my-profile/my-profile.component.css
  src/app/user/my-profile/my-profile.component.html
  src/app/user/promote/promote.component.html
  src/app/user/user.model.ts
  src/app/user/user.service.ts
  src/app/user/workshop-validation/workshop-validation.component.html
  src/assets/img/PowerOn_Black.png
  src/styles.css
Labels: update

#357 Update 2.2.5
  src/app/user/link/link.component.html
  src/app/user/link/my-links/my-links.component.html
Labels: update

#358 Fix: Sign and Link
  src/app/user/link/link.component.css
  src/app/user/link/link.component.html
  src/app/user/link/link.component.ts
  src/app/user/link/my-links/my-links.component.css
  src/app/user/link/my-links/my-links.component.html
  src/app/user/signature/signature.service.ts
Labels: fix

#359 Update 2.2.5
  src/app/company/company.service.ts
  src/app/user/cv/cv.component.ts
  src/app/user/link/link.component.css
  src/app/user/link/link.component.html
  src/app/user/link/link.component.ts
  src/app/user/link/my-links/my-links.component.css
  src/app/user/link/my-links/my-links.component.html
  src/app/user/signature/signature.service.ts
  src/app/user/user.service.ts
  src/app/user/workshops/ticket.service.ts
Labels: update

#361 Fix: Fix schedule
  src/app/landing-page/schedule/schedule.component.html
  src/app/user/user.service.ts
Labels: feature

#360 Feature: Turn SINFO logo into home button
  src/app/auth/login/login.component.css
  src/app/auth/login/login.component.html
Labels: feature

#362 Update 2.2.7
  src/app/auth/login/login.component.css
  src/app/auth/login/login.component.html
  src/app/landing-page/schedule/schedule.component.html
  src/app/user/link/my-links/my-links.component.html
  src/app/user/user.service.ts
Labels: update

#364 Fix: Change share permissions button to toggle
  src/app/user/link/my-links/my-links.component.html
  src/app/user/link/my-links/my-links.component.ts
Labels: fix

#366 Fix: Workshop buttons with material and logo
  src/app/user/workshops/workshop/register-button.component.css
  src/app/user/workshops/workshop/register-button.component.html
  src/app/user/workshops/workshop/workshop.component.html
Labels: fix

#367 Fix: Fixed website session visuals
  src/app/session/session.component.css
  src/app/session/session.component.html
  src/app/session/session.component.ts
Labels: fix

#369 Update 2.2.9
  src/app/partials/menu/menu.component.html
  src/app/session/session.component.ts
  src/app/user/user.component.html
  src/app/user/user.component.ts
Labels: update

#371 Update 2.3.0
  src/app/user/link/my-links/my-links.component.css
  src/app/user/link/my-links/my-links.component.html
Labels: update

#372 Fix: Fix scroll
  src/app/auth/login/login.component.css
  src/app/landing-page/landing-page.component.css
  src/app/landing-page/partners/partners.component.css
  src/app/landing-page/partners/partners.component.html
  src/app/landing-page/schedule/schedule.component.css
  src/app/landing-page/schedule/schedule.component.html
  src/app/landing-page/sponsors/sponsors.component.css
  src/app/landing-page/stands/stands.component.css
  src/app/partials/menu/menu.component.css
  src/app/partials/sidebar/sidebar.component.css
  src/app/session/session.component.css
  src/app/speakers/speaker/speaker.component.css
  src/app/speakers/speakers.component.css
  src/app/sponsor/sponsor.component.css
  src/app/team/team.component.css
  src/app/user/achievements/achievement/achievement.component.css
  src/app/user/achievements/achievements.component.css
  src/app/user/checkin/checkin.component.css
  src/app/user/downloads/manage-downloads/manage-downloads.component.css
  src/app/user/link/my-links/my-links.component.css
  src/app/user/my-profile/my-profile.component.css
  src/app/user/promocodes/promocodes.component.css
  src/app/user/speed-dates/speed-dates.component.css
  src/app/user/survey/survey.component.css
  src/app/user/user.component.css
  src/styles.css
Labels: fix
